Repository GEOS-ESM/GEOSgcm_GridComp, pull requests merged in 2020-05, with the labels that each got.

#272 Update to Baselibs 6.0.12 in CI
  .circleci/config.yml
Labels: 0 diff structural

#280 Sync dev 2 master
  .circleci/config.yml
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/README.md
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/examples/mo_load_coefficients.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/extensions/solar_variability/mo_solar_variability.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/extensions/solar_variability/rrtmgp-solar-var-tables.nc
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/rrtmgp/kernels-openacc/mo_gas_optics_kernels.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/rrtmgp/kernels/mo_gas_optics_kernels.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/rrtmgp/mo_gas_concentrations.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/rrtmgp/mo_gas_optics_rrtmgp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/rte/kernels-openacc/mo_rte_solver_kernels.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/rte/kernels/mo_rte_solver_kernels.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/rte/mo_optical_props.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/rte/mo_rte_lw.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOS_RadiationShared/RRTMGP/rte/mo_source_functions.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/GEOS_IrradGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSsolar_GridComp/GEOS_SolarGridComp.F90
Labels: 0 diff

#283 Fixes #282. Fix for master pulls
  .circleci/config.yml
Labels: 0 diff structural

#284 Update Externals for FV3 GC 1.1.1
  Externals.cfg
Labels: 0 diff, bugfix

#285 Sync develop into master
  .circleci/config.yml
  Externals.cfg
Labels: 0 diff, bugfix
