Repository GEOS-ESM/GEOSgcm_GridComp, pull requests merged in 2020-04, with the labels that each got.

#247 Bugfix/narnold1/#201 scm fixes
  GEOSagcm_GridComp/GEOSsuperdyn_GridComp/GEOSdatmodyn_GridComp/GEOS_DatmoDynGridComp.F90
Labels: 0 diff trivial, bugfix

#240 New Surface parameter resource file
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOS_LandGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOS_CatchCNGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/catchmentCN.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/compute_FPAR_CDF_M09.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/dbg_cnlsm_offline.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/math_routines.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/GEOS_CatchGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOSvegdyn_GridComp/GEOS_VegdynGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/Shared/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlandice_GridComp/GEOS_LandIceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_CICE4ColumnPhysGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_OpenWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SimpleSeaiceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Shared/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Shared/GEOS_SurfaceGridComp.rc
Labels: 0 diff, enhancement

#255 bug fix: removed local declaration of SURFLAY in RUN0
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/GEOS_CatchGridComp.F90
Labels: 0 diff, bugfix

#251 Feature/jstassi/mk restarts on sles12
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/mk_restarts/mk_Restarts
Labels: 0 diff, bugfix

#187 Online calculation of lightning flash rate for GEOSCHEMchem
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
Labels: 0 diff

#257 Uptick chem because required with GEOSgcm_GridComp #187
  Externals.cfg
Labels: 0 diff

#253 Fixed DTDT_moist issue
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
Labels: 0 diff, bugfix

#250 Bugfix/yury/tskinifix
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
Labels: 0 diff, bugfix

#174 Feature/yury/obio
  GEOS_GcmGridComp.F90
  GEOSdataatm_GridComp/GEOS_DataAtmGridComp.F90
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
  GEOSogcm_GridComp/GEOSoceanbiogeochem_GridComp/GEOS_OceanbiogeochemGridComp.F90
  GEOSogcm_GridComp/GEOSoradbio_GridComp/GEOS_OradBioGridComp.F90
  GEOSogcm_GridComp/GEOSoradbio_GridComp/sfcirr.F90
Labels: 0 diff

#259 Connect MOIST RI and RL to CHEM, for GMI CloudJ
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
Labels: 0 diff

#260 Fixes #258. Allow GNU to run
  GEOS_GcmGridComp.F90
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
Labels: 0 diff

#263 Update config.yml
  .circleci/config.yml
Labels: 0 diff structural

#265 Update CircleCI to use 6.0.11
  .circleci/config.yml
Labels: 0 diff structural

#267 Fixes #266. Update CODEOWNERS for Surface
  .github/CODEOWNERS
Labels: 0 diff structural

#269 Hand merge master to develop for codeowners
  .github/CODEOWNERS
Labels: 0 diff structural

#268 Merge master to develop for codeowners
  .circleci/config.yml
Labels: 0 diff structural
