Repository GEOS-ESM/GEOSgcm_GridComp, pull requests merged in 2020-10, with the labels that each got.

#357 Include new diagnostics for the constraints as well as a new option t…
  GEOSagcm_GridComp/GEOS_AgcmGridComp.F90
Labels: 0 diff

#358 Feature/san akel/aoil v2.0 dev
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_OpenWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SimpleSeaiceGridComp.F90
Labels: 0 diff, bugfix

#355 add TOA RRTMG Band6 (window region) IR diagnostics for Allie
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/GEOS_IrradGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/RRTMG/rrtmg_lw/gcm_model/src/gpu_rrtmg_lw_rtrnmc.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/RRTMG/rrtmg_lw/gcm_model/src/rrtmg_lw_rad.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/RRTMG/rrtmg_lw/gcm_model/src/rrtmg_lw_rtrn.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/RRTMG/rrtmg_lw/gcm_model/src/rrtmg_lw_rtrnmr.F90
Labels: 0 diff

#360 Add Github CI
  .github/workflows/workflow.yml
Labels: 0 diff structural

#364 Sync develop into main
  .github/workflows/workflow.yml
  GEOSagcm_GridComp/GEOS_AgcmGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/GEOS_IrradGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/RRTMG/rrtmg_lw/gcm_model/src/gpu_rrtmg_lw_rtrnmc.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/RRTMG/rrtmg_lw/gcm_model/src/rrtmg_lw_rad.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/RRTMG/rrtmg_lw/gcm_model/src/rrtmg_lw_rtrn.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/RRTMG/rrtmg_lw/gcm_model/src/rrtmg_lw_rtrnmr.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_OpenWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SimpleSeaiceGridComp.F90
Labels: 0 diff

#366 Add Docker authentication for pulls
  .circleci/config.yml
  .github/workflows/workflow.yml
Labels: 0 diff structural

#367 Restructure DO_OBIO
  GEOS_GcmGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_ObioGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
  GEOSogcm_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/GEOS_OceanbiogeochemGridComp.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/carbon.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/co2calc_SWS.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/daysetbio.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/definebio.h
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/definetab.h
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/drtsafe.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/kloop.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/ppco2.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/ptend.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/setbio.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/sink.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/ta_iter_SWS.F90
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OradBioGridComp/GEOS_OradBioGridComp.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/aasack.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/clrtrans.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/comlte.h
  GEOSogcm_GridComp/GEOS_OradBioGridComp/daysetrad.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/define.h
  GEOSogcm_GridComp/GEOS_OradBioGridComp/definebio.h
  GEOSogcm_GridComp/GEOS_OradBioGridComp/edeu.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/glight.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/lidata.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/lidatatm.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/ocalbedo.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/setlte.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/setsfclte.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/sfcirr.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/slingo.F90
  GEOSogcm_GridComp/GEOS_OradGridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OradGridComp/GEOS_OradGridComp.F90
  GEOSogcm_GridComp/GEOSoceanbiosimple_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOSoceanbiosimple_GridComp/GEOS_OceanbioGridComp.F90
Labels: 0 diff structural

#349 Updates to CatchCN GridComp so it can reproduce Fanwei's science-tested LDASsa version of CatchCN
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOS_CatchCNGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/catchmentCN.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/dbg_cnlsm_offline.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/mk_restarts/mk_Restarts
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Shared/GEOS_SurfaceGridComp.rc
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Shared/SurfParams.F90
Labels: 0 diff, Non 0-diff

#369 Sync dev into main
  .circleci/config.yml
  .github/workflows/workflow.yml
  GEOS_GcmGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOS_CatchCNGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/catchmentCN.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/dbg_cnlsm_offline.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/mk_restarts/mk_Restarts
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_ObioGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Shared/GEOS_SurfaceGridComp.rc
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Shared/SurfParams.F90
  GEOSogcm_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/GEOS_OceanbiogeochemGridComp.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/carbon.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/co2calc_SWS.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/daysetbio.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/definebio.h
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/definetab.h
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/drtsafe.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/kloop.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/ppco2.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/ptend.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/setbio.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/sink.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/ta_iter_SWS.F90
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OradBioGridComp/GEOS_OradBioGridComp.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/aasack.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/clrtrans.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/comlte.h
  GEOSogcm_GridComp/GEOS_OradBioGridComp/daysetrad.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/define.h
  GEOSogcm_GridComp/GEOS_OradBioGridComp/definebio.h
  GEOSogcm_GridComp/GEOS_OradBioGridComp/edeu.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/glight.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/lidata.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/lidatatm.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/ocalbedo.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/setlte.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/setsfclte.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/sfcirr.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/slingo.F90
  GEOSogcm_GridComp/GEOS_OradGridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OradGridComp/GEOS_OradGridComp.F90
  GEOSogcm_GridComp/GEOSoceanbiosimple_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOSoceanbiosimple_GridComp/GEOS_OceanbioGridComp.F90
Labels: 0 diff
