Repository GEOS-ESM/GEOSgcm_GridComp, pull requests merged in 2021-12, with the labels that each got.

#488 5deg ocean (MOM6) configuration
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/geos/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/MOM_input
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/MOM_override
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/MOM_parameter_doc.all
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/data_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/g5aodas_diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/g5aodas_input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/README
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/README.md
Labels: enhancement, 0 diff, :sun_with_face: MOM6 coupled model

#491 Fixed missing verify status of iDUAL_OCEAN in GEOS_OceanGridComp.F90
  GEOSogcm_GridComp/GEOS_OceanGridComp/GEOS_OceanGridComp.F90
Labels: 0 diff, bugfix

#493 Clean up CircleCI
  .circleci/config.yml
Labels: 0 diff trivial

#496 Make big 5-d buffer in Moist optional
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
Labels: 0 diff

#498 Sync develop into main
  .circleci/config.yml
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
  GEOSogcm_GridComp/GEOS_OceanGridComp/GEOS_OceanGridComp.F90
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/geos/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/MOM_input
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/MOM_override
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/MOM_parameter_doc.all
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/data_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/g5aodas_diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/g5aodas_input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/README
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/README.md
Labels: 0 diff

#438 make_bcs is now open to public
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/CombineRasters.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/FillMomGrid.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/clsm_plots.pro
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/comp_CATCHCN_AlbScale_parameters.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/compare_bcs.pro
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/create_README.csh
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/create_vegdyn_ndvi.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/irrg_model.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkCatchParam.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkLISTilesPara.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkLandRaster.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkMOMAquaRaster.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkSMAPTilesPara.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkSMAPTilesPara_v2.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mk_runofftbl.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mod_process_hres_data.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/rasterize.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/rmTinyCatchParaMod.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/sibalb.f
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/zenith.f
Labels: enhancement, 0 diff

#451 Moved lightning flash rate (LFR) calculation from MOIST to ChemEnv
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
Labels: 0 diff

#459 Closes #458. Makes Satsim Subcolumns Resolution-Based
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSsatsim_GridComp/GEOS_SatsimGridComp.F90
Labels: 0 diff, Non 0-diff

#502 Sync develop into main
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSsatsim_GridComp/GEOS_SatsimGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/CombineRasters.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/FillMomGrid.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/clsm_plots.pro
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/comp_CATCHCN_AlbScale_parameters.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/compare_bcs.pro
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/create_README.csh
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/create_vegdyn_ndvi.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/irrg_model.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkCatchParam.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkLISTilesPara.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkLandRaster.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkMOMAquaRaster.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkSMAPTilesPara.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mkSMAPTilesPara_v2.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mk_runofftbl.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/mod_process_hres_data.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/rasterize.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/rmTinyCatchParaMod.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/sibalb.f
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/zenith.f
Labels: Non 0-diff

#499 Bugfix/wjiang/dealloc mask
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM40_GridComp/GEOS_CatchCNCLM40GridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM45_GridComp/GEOS_CatchCNCLM45GridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/GEOS_CatchGridComp.F90
Labels: 0 diff trivial, bugfix

#503 fix timers in catchcn
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM40_GridComp/GEOS_CatchCNCLM40GridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM45_GridComp/GEOS_CatchCNCLM45GridComp.F90
Labels: 0 diff trivial, bugfix

#505 Sync develop into main
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM40_GridComp/GEOS_CatchCNCLM40GridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM45_GridComp/GEOS_CatchCNCLM45GridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/GEOS_CatchGridComp.F90
Labels: 0 diff

#507 Fixes #506. Initialize uninitialized part of selffac array
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/RRTMG/rrtmg_lw/gcm_model/src/rrtmg_lw_setcoef.F90
Labels: 0 diff

#479 Adding SHOC+EDMF updates
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/cloudnew.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/partition_pdf.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/GEOS_TurbulenceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/edmf.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/edmfparams.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/scm_surface.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/shoc.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/shocparams.F90
  GEOSagcm_GridComp/GEOSsuperdyn_GridComp/GEOSdatmodyn_GridComp/GEOS_DatmoDynGridComp.F90
Labels: enhancement, Non 0-diff

#510 add CLDXXSW diagnostics and many cosmetic changes to Solar GC
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/GEOS_IrradGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/RRTMG/rrtmg_lw/gcm_model/src/rrtmg_lw_setcoef.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSsolar_GridComp/GEOS_SolarGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSsolar_GridComp/RRTMG/rrtmg_sw/gcm_model/src/rrtmg_sw_rad.F90
Labels: 0 diff
