Repository GEOS-ESM/GEOSgcm_GridComp, pull requests merged in 2021-03, with the labels that each got.

#412 Remove unneeded gfortran ifdefs
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOSroute_GridComp/GEOS_RouteGridComp.F90
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
Labels: 0 diff

#377 dso for mom5 and mom6
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/CMakeLists.txt
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/MOM6_GEOSPlug.F90
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM_GEOS5PlugMod/CMakeLists.txt
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90
Labels: 0 diff

#410 Add Python Transition Team Codeowner
  .github/CODEOWNERS
Labels: 0 diff structural, 0 diff trivial

#411 Fixed a bug in rotation angle for surface ocean stress.
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/MOM6_GEOSPlug.F90
Labels: 0 diff, :sun_with_face: MOM6 coupled model, bugfix

#409 Fixes #121. Fix gustiness calculations
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOS_CatchCNGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/GEOS_CatchGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_CICE4ColumnPhysGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_OpenWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SimpleSeaiceGridComp.F90
Labels: 0 diff, Non 0-diff

#414 Fixed MOM6 dianostics options
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_app/360x210/diag_table
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_app/360x320/diag_table
Labels: 0 diff trivial, bugfix

#416 For update to MOM6 geos/v2.0.0
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
Labels: 0 diff structural

#419 Sync dev into main
  .github/CODEOWNERS
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOS_CatchCNGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/GEOS_CatchGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOSroute_GridComp/GEOS_RouteGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_CICE4ColumnPhysGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_OpenWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SimpleSeaiceGridComp.F90
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/CMakeLists.txt
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/MOM6_GEOSPlug.F90
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_app/360x210/diag_table
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_app/360x320/diag_table
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM_GEOS5PlugMod/CMakeLists.txt
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90
Labels: 0 diff

#401 Revive OceanBioGeoChem
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/GEOS_OceanbiogeochemGridComp.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/kloop.F90
  GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/ta_iter_SWS.F90
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/GEOS_OradBioGridComp.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/clrtrans.F90
Labels: 0 diff, bugfix

#396 Fixes #394 and #395 (ta and obio dual ocean)
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
Labels: Contingent - DNA, bug, bugfix
