Repository GEOS-ESM/GEOSgcm_GridComp, pull requests merged in 2021-06, with the labels that each got.

#439 Update CI image to Baselibs 6.2.4
  .circleci/config.yml
  .github/workflows/workflow.yml
Labels: 0 diff, 0 diff structural

#440 Bugfix/cakelle2/restore cnv mfc
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
Labels: 0 diff trivial, bugfix

#437 create a new top level seaice container component
  GEOSogcm_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90
  GEOSogcm_GridComp/GEOSseaice_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOSseaice_GridComp/GEOS_SeaIceGridComp.F90
  GEOSogcm_GridComp/GEOSseaice_GridComp/GEOSdataseaice_GridComp/GEOS_DataSeaIceGridComp.F90
Labels: 0 diff, 0 diff structural, enhancement

#441 Sync develop into main
  .circleci/config.yml
  .github/workflows/workflow.yml
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
  GEOSogcm_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
  GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90
  GEOSogcm_GridComp/GEOSseaice_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOSseaice_GridComp/GEOS_SeaIceGridComp.F90
  GEOSogcm_GridComp/GEOSseaice_GridComp/GEOSdataseaice_GridComp/GEOS_DataSeaIceGridComp.F90
Labels: 0 diff
