Repository GEOS-ESM/GEOSgcm_GridComp, pull requests merged in 2021-01, with the labels that each got.

#389 Use CONFIGURE_DEPENDS with GLOB
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/CMakeLists.txt
Labels: 0 diff, 0 diff structural

#393 Add ASSERTs to RRTMG to test input sanity
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSirrad_GridComp/RRTMG/rrtmg_lw/gcm_model/src/rrtmg_lw_rad.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSsolar_GridComp/RRTMG/rrtmg_sw/gcm_model/src/rrtmg_sw_rad.F90
Labels: 0 diff

#392 Add partition option for regrid
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/mk_restarts/mk_Restarts
Labels: 0 diff

#391 Update CODEOWNERS
  .github/CODEOWNERS
Labels: 0 diff structural

#397 Update CI image to 6.0.27. Ignore some files
  .circleci/config.yml
  .github/workflows/workflow.yml
Labels: 0 diff trivial
