Repository GEOS-ESM/GEOSgcm_GridComp, pull requests merged in 2021-11, with the labels that each got.

#471 Refactors ESMF_AttributeGet to ESMF_InfoGet for FRIENDLY's
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/GEOS_TurbulenceGridComp.F90
  GEOSagcm_GridComp/GEOSsuperdyn_GridComp/GEOSdatmodyn_GridComp/GEOS_DatmoDynGridComp.F90
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
Labels: 0 diff

#467 add error checking in mk_restarts executables
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/SaltImpConverter.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/SaltIntSplitter.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/Scale_Catch.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/Scale_CatchCN.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_CatchCNRestarts.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_CatchRestarts.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_GEOSldasRestarts.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_LakeLandiceSaltRestarts.F90
Labels: 0 diff

#468 Support update to MOM6
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
Labels: enhancement, 0 diff

#474 Fixes #473 - cmake stub bug
  GEOSogcm_GridComp/GEOS_OceanGridComp/CMakeLists.txt
Labels: 0 diff structural

#476 Update CI to Baselibs 6.2.8
  .circleci/config.yml
Labels: 0 diff

#477 Timing from MOM6
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/MOM6_GEOSPlug.F90
Labels: enhancement, 0 diff

#478 add in support of quarter degree MOM6 and its working within ADAS
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/MOM_input
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/MOM_override
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/data_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/g5aodas_diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/g5aodas_input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/input.nml
Labels: enhancement, 0 diff trivial

#482 Sync develop into main
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE/auto_pr_to_mapl3.md
  .github/workflows/push-to-develop.yml
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/SaltImpConverter.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/SaltIntSplitter.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/Scale_Catch.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/Scale_CatchCN.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_CatchCNRestarts.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_CatchRestarts.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_GEOSldasRestarts.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_LakeLandiceSaltRestarts.F90
  GEOSogcm_GridComp/GEOS_OceanGridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/MOM6_GEOSPlug.F90
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/MOM_input
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/MOM_override
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/data_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/g5aodas_diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/g5aodas_input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
Labels: 0 diff

#484 replace _RETURN(_SUCCESS)
  .github/workflows/workflow.yml
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/Scale_Catch.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/Scale_CatchCN.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_CatchCNRestarts.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_CatchRestarts.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_GEOSldasRestarts.F90
Labels: 0 diff, 0 diff trivial, 0 diff structural

#485 Update CODEOWNERS for Surface Move
  .github/CODEOWNERS
Labels: 0 diff structural

#487 Sync develop into main
  .github/CODEOWNERS
  .github/workflows/workflow.yml
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/Scale_Catch.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/Scale_CatchCN.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_CatchCNRestarts.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_CatchRestarts.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_GEOSldasRestarts.F90
Labels: 0 diff
