Repository GEOS-ESM/GEOSgcm_GridComp, pull requests merged in 2022-03, with the labels that each got.

#547 Feature/rtodling/gcm 1 12 4 tskinice realfix
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_CICE4ColumnPhysGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SimpleSeaiceGridComp.F90
Labels: 0 diff trivial, 0 diff structural, bugfix

#562 Add option to read ocean _data_ using `ExtData`
  GEOSogcm_GridComp/GEOS_OceanGridComp/GEOSdatasea_GridComp/GEOS_DataSeaGridComp.F90
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
  GEOSogcm_GridComp/GEOS_OradBioGridComp/GEOS_OradBioGridComp.F90
  GEOSogcm_GridComp/GEOS_OradGridComp/GEOS_OradGridComp.F90
  GEOSogcm_GridComp/GEOSseaice_GridComp/GEOSdataseaice_GridComp/GEOS_DataSeaIceGridComp.F90
Labels: enhancement, 0 diff

#546 Run History in predictor
  GEOS_GcmGridComp.F90
Labels: enhancement, 0 diff

#561 Updates to support Spack
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSgwd_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSradiation_GridComp/GEOSsolar_GridComp/RRTMG/rrtmg_sw/gcm_model/src/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM40_GridComp/CLM40/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM40_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM45_GridComp/CLM45/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM45_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOSroute_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOSvegdyn_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlandice_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSsuperdyn_GridComp/GEOSdatmodyn_GridComp/CMakeLists.txt
  GEOSmkiau_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OceanGridComp/GEOSdatasea_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OradGridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOSseaice_GridComp/GEOSdataseaice_GridComp/CMakeLists.txt
Labels: 0 diff

#559 Feature/ltakacs/r21c observed precip
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
Labels: 0 diff, bugfix

#551 Remove Ocean Grid Comp
  GEOSogcm_GridComp/.gitignore
  GEOSogcm_GridComp/GEOS_OceanGridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OceanGridComp/GEOS_OceanGridComp.F90
  GEOSogcm_GridComp/GEOS_OceanGridComp/GEOSdatasea_GridComp/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OceanGridComp/GEOSdatasea_GridComp/GEOS_DataSeaGridComp.F90
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/.gitignore
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/MOM6_GEOSPlug.F90
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/MOM_input
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/MOM_override
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/data_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/g5aodas_diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/g5aodas_input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/1440x1080/input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x210/MOM_input
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x210/MOM_override
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x210/MOM_parameter_doc.all
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x210/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x210/data_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x210/diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x210/input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/MOM_input
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/MOM_override
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/data_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/geos/MOM_input
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/geos/MOM_override
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/geos/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/soca/MOM_input
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/soca/MOM_override
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/360x320/soca/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/MOM_input
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/MOM_override
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/MOM_parameter_doc.all
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/data_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/g5aodas_diag_table
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/g5aodas_input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/72x36/input.nml
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_app/README.md
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM_GEOS5PlugMod/.gitignore
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM_GEOS5PlugMod/CMakeLists.txt
  GEOSogcm_GridComp/GEOS_OceanGridComp/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90
Labels: 0 diff structural

#558 For sea ice development: add CICE6 and SIS2 sea ice models
  GEOSogcm_GridComp/GEOSseaice_GridComp/CICE_GEOSPlug/.gitignore
Labels: enhancement, 0 diff
