Repository GEOS-ESM/GEOSgcm_GridComp, pull requests merged in 2024-01, with the labels that each got.

#876 Changes needed to allow GNU build of wave GEOS
  GEOSogcm_GridComp/GEOSseaice_GridComp/CMakeLists.txt
  GEOSwgcm_GridComp/CMakeLists.txt
  GEOSwgcm_GridComp/GEOSumwm_GridComp/.gitignore
  GEOSwgcm_GridComp/GEOSumwm_GridComp/CMakeLists.txt
  GEOSwgcm_GridComp/GEOSumwm_GridComp/GEOS_UMWMGridComp.F90
  GEOSwgcm_GridComp/GEOSumwm_GridComp/umwm_cmake/CMakeLists.txt
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/.gitignore
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/CMakeLists.txt
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/ww3_multi_esmf/CMakeLists.txt
Labels: 0 diff

#883 NWP patches
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSgwd_GridComp/GEOS_GwdGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSgwd_GridComp/ncar_gwd/gw_common.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSgwd_GridComp/ncar_gwd/gw_convect.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSgwd_GridComp/ncar_gwd/gw_drag.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_BACM_1M_InterfaceMod.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_GFDL_1M_InterfaceMod.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/Process_Library.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/uwshcu.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/GEOS_TurbulenceGridComp.F90
Labels: Non 0-diff

#879 SHOC-EDMF updates
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/Process_Library.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/GEOS_TurbulenceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/edmf.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/shoc.F90
Labels: 0 diff

#888 Enable STDC ifdef for zip.c for Spack builds
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/makebcs/CMakeLists.txt
Labels: 0 diff

#881 Restore the MTRI bundle
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
Labels: 0 diff

#882 Refine check for allowable bcs versions to be run with CatchCN
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_catchANDcnRestarts.F90
Labels: 0 diff trivial, bugfix

#889 Update LONG_NAME of DO3DT_ANA
  GEOSagcm_GridComp/GEOS_AgcmGridComp.F90
Labels: 0 diff trivial

#872 WMMA
  CMakeLists.txt
  GEOS_GcmGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_OpenWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/GEOS_TurbulenceGridComp.F90
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
  GEOSogcm_GridComp/GEOSseaice_GridComp/CMakeLists.txt
  GEOSwgcm_GridComp/CMakeLists.txt
  GEOSwgcm_GridComp/GEOS_WgcmGridComp.F90
  GEOSwgcm_GridComp/GEOSumwm_GridComp/.gitignore
  GEOSwgcm_GridComp/GEOSumwm_GridComp/CMakeLists.txt
  GEOSwgcm_GridComp/GEOSumwm_GridComp/GEOS_UMWMGridComp.F90
  GEOSwgcm_GridComp/GEOSumwm_GridComp/UMWM.rc
  GEOSwgcm_GridComp/GEOSumwm_GridComp/UMWM_ExtData.yaml
  GEOSwgcm_GridComp/GEOSumwm_GridComp/umwm_cmake/CMakeLists.txt
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/.gitignore
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/CMakeLists.txt
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/GEOS_WaveWatchGridComp.F90
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/ww3_multi_esmf/CMakeLists.txt
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/ww3_multi_esmf/run_w3adc.sh
  GEOSwgcm_GridComp/WGCM.rc
  GEOSwgcm_GridComp/bl_seaspray.F90
Labels: enhancement, 0 diff

#894 Sync develop into main
  .circleci/config.yml
  CMakeLists.txt
  GEOS_GcmGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/Process_Library.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_OpenWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/makebcs/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/mk_catchANDcnRestarts.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/GEOS_TurbulenceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/edmf.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSturbulence_GridComp/shoc.F90
  GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
  GEOSogcm_GridComp/GEOSseaice_GridComp/CMakeLists.txt
  GEOSwgcm_GridComp/CMakeLists.txt
  GEOSwgcm_GridComp/GEOS_WgcmGridComp.F90
  GEOSwgcm_GridComp/GEOSumwm_GridComp/.gitignore
  GEOSwgcm_GridComp/GEOSumwm_GridComp/CMakeLists.txt
  GEOSwgcm_GridComp/GEOSumwm_GridComp/GEOS_UMWMGridComp.F90
  GEOSwgcm_GridComp/GEOSumwm_GridComp/UMWM.rc
  GEOSwgcm_GridComp/GEOSumwm_GridComp/UMWM_ExtData.yaml
  GEOSwgcm_GridComp/GEOSumwm_GridComp/umwm_cmake/CMakeLists.txt
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/.gitignore
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/CMakeLists.txt
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/GEOS_WaveWatchGridComp.F90
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/ww3_multi_esmf/CMakeLists.txt
  GEOSwgcm_GridComp/GEOSwavewatch_GridComp/ww3_multi_esmf/run_w3adc.sh
  GEOSwgcm_GridComp/WGCM.rc
  GEOSwgcm_GridComp/bl_seaspray.F90
Labels: 0 diff
