Repository GEOS-ESM/GEOSgcm_GridComp, pull requests merged in 2024-12, with the labels that each got.

#1032 update LONG_NAME attributes to match M21C file specs; conservative regridding of (obs) PRECIP_FILE inputs
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOS_CatchCNGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM40_GridComp/GEOS_CatchCNCLM40GridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/GEOS_CatchGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOSroute_GridComp/GEOS_RouteGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOSvegdyn_GridComp/GEOS_VegdynGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlandice_GridComp/GEOS_LandIceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_CICE4ColumnPhysGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_OpenWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SeaiceInterfaceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SimpleSeaiceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/CatchmentRst.F90
Labels: documentation, 0 diff

#1021 Satisfy CHEM imports for Lopez LFR scheme
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
Labels: 0 diff

#1030 do not terminate SURFSTAT when running with CICE6
  GEOSdataatm_GridComp/GEOS_DataAtmGridComp.F90
Labels: 0 diff

#1037 v11: Add dependency to fms_r4
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/CMakeLists.txt
Labels: 0 diff

#954 Add gigatraj grid comp
  CMakeLists.txt
  GEOS_GcmGridComp.F90
  GEOSagcm_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOS_AgcmGridComp.F90
  GEOSagcm_GridComp/GEOSsuperdyn_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSsuperdyn_GridComp/GEOS_SuperdynGridComp.F90
  GEOSgigatraj_GridComp/.gitignore
  GEOSgigatraj_GridComp/CMakeLists.txt
  GEOSgigatraj_GridComp/GEOS_Giga_InterOp.F90
  GEOSgigatraj_GridComp/GEOS_GigatrajGridComp.F90
  GEOSgigatraj_GridComp/Gigatraj_Utils.F90
Labels: enhancement, 0 diff

#1022 updated refresh method registration using newly introduced MAPL flag
  GEOSogcm_GridComp/GEOSseaice_GridComp/CICE_GEOSPlug/CICE_GEOSPlug.F90
Labels: 0 diff

#1034 [MKIAU] Initial prototype of a CFFI-based fortran/python bridge
  GEOSmkiau_GridComp/CMakeLists.txt
  GEOSmkiau_GridComp/GEOS_mkiauGridComp.F90
  GEOSmkiau_GridComp/pyMKIAU/.gitignore
  GEOSmkiau_GridComp/pyMKIAU/README.md
  GEOSmkiau_GridComp/pyMKIAU/interface/interface.c
  GEOSmkiau_GridComp/pyMKIAU/interface/interface.f90
  GEOSmkiau_GridComp/pyMKIAU/interface/interface.h
  GEOSmkiau_GridComp/pyMKIAU/interface/interface.py
  GEOSmkiau_GridComp/pyMKIAU/pyMKIAU/__init__.py
  GEOSmkiau_GridComp/pyMKIAU/pyMKIAU/core.py
  GEOSmkiau_GridComp/pyMKIAU/pyMKIAU/cuda_profiler.py
  GEOSmkiau_GridComp/pyMKIAU/pyMKIAU/f_py_conversion.py
  GEOSmkiau_GridComp/pyMKIAU/setup.py
Labels: 0 diff structural
