Repository GEOS-ESM/GEOSgcm_GridComp, pull requests merged in 2025-01, with the labels that each got.

#1038 .yaml file for JRA55-DO dataset
  GEOSdataatm_GridComp/CMakeLists.txt
  GEOSdataatm_GridComp/JRA55-DO_DataAtm_Forcings_ExtData.yaml
Labels: 0 diff

#1040 a few fixes to DataAtm with corrections to SW, SH and EVAP etc.
  GEOSdataatm_GridComp/GEOS_DataAtmGridComp.F90
Labels: 0 diff

#1042 [NDSL] pyMoist Interface Platform Compatibility
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/interface/cffi_lib/interface.py
Labels: 0 diff structural

#1045 Update CI to orb 4
  .circleci/config.yml
Labels: 0 diff trivial

#1043 Sync develop into main
  .circleci/config.yml
  CMakeLists.txt
  GEOS_GcmGridComp.F90
  GEOSagcm_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOS_AgcmGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOS_PhysicsGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOS_CatchCNGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatchCN_GridComp/GEOScatchCNCLM40_GridComp/GEOS_CatchCNCLM40GridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOScatch_GridComp/GEOS_CatchGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOSroute_GridComp/GEOS_RouteGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOSvegdyn_GridComp/GEOS_VegdynGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlandice_GridComp/GEOS_LandIceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_CICE4ColumnPhysGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_OpenWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SeaiceInterfaceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SimpleSeaiceGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/CatchmentRst.F90
  GEOSagcm_GridComp/GEOSsuperdyn_GridComp/CMakeLists.txt
  GEOSagcm_GridComp/GEOSsuperdyn_GridComp/GEOS_SuperdynGridComp.F90
  GEOSdataatm_GridComp/CMakeLists.txt
  GEOSdataatm_GridComp/GEOS_DataAtmGridComp.F90
  GEOSdataatm_GridComp/JRA55-DO_DataAtm_Forcings_ExtData.yaml
  GEOSgigatraj_GridComp/.gitignore
  GEOSgigatraj_GridComp/CMakeLists.txt
  GEOSgigatraj_GridComp/GEOS_Giga_InterOp.F90
  GEOSgigatraj_GridComp/GEOS_GigatrajGridComp.F90
  GEOSgigatraj_GridComp/Gigatraj_Utils.F90
  GEOSmkiau_GridComp/CMakeLists.txt
  GEOSmkiau_GridComp/GEOS_mkiauGridComp.F90
  GEOSmkiau_GridComp/pyMKIAU/.gitignore
  GEOSmkiau_GridComp/pyMKIAU/README.md
  GEOSmkiau_GridComp/pyMKIAU/interface/interface.c
  GEOSmkiau_GridComp/pyMKIAU/interface/interface.f90
  GEOSmkiau_GridComp/pyMKIAU/interface/interface.h
  GEOSmkiau_GridComp/pyMKIAU/interface/interface.py
  GEOSmkiau_GridComp/pyMKIAU/pyMKIAU/__init__.py
  GEOSmkiau_GridComp/pyMKIAU/pyMKIAU/core.py
  GEOSmkiau_GridComp/pyMKIAU/pyMKIAU/cuda_profiler.py
  GEOSmkiau_GridComp/pyMKIAU/pyMKIAU/f_py_conversion.py
  GEOSmkiau_GridComp/pyMKIAU/setup.py
  GEOSogcm_GridComp/GEOSseaice_GridComp/CICE_GEOSPlug/CICE_GEOSPlug.F90
Labels: 0 diff

#1002 v11: Fix for SNOMAS and SRF_TYPE
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/Process_Library.F90
Labels: Non 0-diff, bugfix

#1048 Sync develop into main
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
  GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/Process_Library.F90
Labels: Non 0-diff
